// Generated by M. Yıldıray Meric
// Type definitions for jquery-multi-select.js
// Project: https://github.com/lou/multi-select
// Definitions by: M. Yıldıray Meric <yildiray.meric@argela.com.tr>

interface MultiSelectStatic {
}

// jQuery extensions
interface JQueryStatic {
    multiSelect: (options?: any) => void;
}

interface JQuery {
    /*  Note: options are same options as used by the translate function. Alternatively by
     setting init option or translation option 'useDataAttrOptions = true' the Options
     for translation will be read and cached in the elements data-i18n-options attribute.
     */
    multiSelect: (options?: any) => void;
}

declare var multiSelect: MultiSelectStatic;

declare module 'multiSelect' {
    export = multiSelect;
}