/**
 * Created by yildirayme on 23.08.2016.
 */

export enum UI_TOPOLOGY_ACTION {
    EDIT_TOPOLOGY = <any>'EDIT_TOPOLOGY',
    VIEW_TOPOLOGY = <any>'VIEW_TOPOLOGY',
    VIEW_PHYSICAL_TOPOLOGY = <any>'VIEW_PHYSICAL_TOPOLOGY',
    NEW_VIRTUAL_TOPOLOGY = <any>'NEW_VIRTUAL_TOPOLOGY',
    NEW_VIRTUAL_TOPOLOGY_REQUEST = <any>'NEW_VIRTUAL_TOPOLOGY_REQUEST',
    NEW_SUPER_TOPOLOGY = <any>'NEW_SUPER_TOPOLOGY'
}