//Auto-generated file, do not modify, use milat_api project to regenerate and update.
export var alarm_codes = {
    "tr": {
        "ControllerDeactivated": "Kontrolcü Deaktive",
        "DBOperationFailed": "Veritabanı İşlemi Başarısız",
        "DeviceIsNotAvailable": "Cihaz Uygun Değil",
        "LinkDown": "Bağlantı Koptu",
        "MvtnDeviceFailed": "Sanal Ağ Cihazı Başarısız",
        "MvtnLinkFailed": "Sanal Ağ Bağlantısı Koptu",
        "MvtnLinkRebuild": "Sanal Ağ Bağlantısı Tekrar Oluşturuldu",
        "SelfLoopDetection": "Döngü Keşfedildi",
        "ForwardingLoopDetection": "İletim Döngüsü Keşfedildi",
        "TsdbProviderNotAvailable": "ZSVT Hizmeti Yok",
        "OpenFlowMessageError": "Hatalı OpenFlow Mesajı",
        "DOSAttackDetected": "DOS Saldırısı Tespit Edildi",
        "SnmpTrapReceived": "SNMP Trap Alındı",
        "ProactivePathFailed": "Önetkin Patika Koptu",
        "MvtnCreated": "Sanal Ağ Oluşturuldu",
        "UnreachableDatabase": "Veritabanına Ulaşılamıyor",
        "EventNotSupportedByCurrentState": "Olay desteklenmiyor",
        "HbaseConnectionError": "HBASE&#39;e bağlanılamıyor",
        "MvtnRejected": "Sanal Ağ Red Edildi",
        "MvtnUpdateAccepted": "Sanal Ağ Güncelleme Kabul Edildi",
        "MvtnUpdateRejected": "Sanal Ağ Güncelleme Red Edildi",
        "MonitorPacketReceived": "Gözcü Paketi Alındı",
        "GaugeEntersAlarm": "Gözcü Alarmı",
        "DeviceModeIsPowerSaver": "Cihaz Enerji Tasarrufu Modunda",
        "ProactivePathRecalculate": "Önetkin Patika Yeniden Hesaplandı",
        "WanCommunicationError": "WAN İletişim Hatası",
        "PolicySelectionNotAchieved": "Politika Seçilemedi",
        "RabbitMQErrorOccured": "RabbitMQ Hatası",
        "RadiusServerErrorOccured": "Radius Sunucu Hatası",
        "LdapClientErrorOccured": "LDAP İstemci Hatası",
        "BgpSpeakerConfigurationError": "BGP Sözcü Konfigürasyon Hatası",
        "BgpSpeakerUnconfigurationError": "BGP Sözcü Nakonfigürasyon Hatası",
        "BgpPeerConfigurationError": "BGP Eş Konfigürasyon Hatası",
        "BgpPeerUnconfigurationError": "BGP Eş Nakonfigürasyon Hatası",
        "BgpPeerConnectionError": "BGP Eş Bağlantı Hatası",
        "NeedEmergencyPolicy": "Acil Durum Politikası Uygulanabilir.",
        "InvalidCredentials": "Geçersiz kullanıcı&#x2F;şifre ile giriş isteği yapıldı."
    },
    "en": {
        "ControllerDeactivated": "Controller Deactivated",
        "DBOperationFailed": "Database Operation Failed",
        "DeviceIsNotAvailable": "Device is N&#x2F;A",
        "LinkDown": "Link Down",
        "MvtnDeviceFailed": "Mvtn Device Failed",
        "MvtnLinkFailed": "Mvtn Link Failed",
        "MvtnLinkRebuild": "Mvtn Link Rebuild",
        "SelfLoopDetection": "Self Loop Detected",
        "ForwardingLoopDetection": "Forwarding Loop Detected",
        "TsdbProviderNotAvailable": "TSDB Provider is N&#x2F;A",
        "OpenFlowMessageError": "OpenFlow Message Error",
        "DOSAttackDetected": "DOS Attack Detected",
        "SnmpTrapReceived": "SNMP Trap Received",
        "ProactivePathFailed": "Proactive Path Failed",
        "MvtnCreated": "MVTN Created",
        "UnreachableDatabase": "Database Unreachable",
        "EventNotSupportedByCurrentState": "Event Not Supported",
        "HbaseConnectionError": "Cannot connect to HBASE",
        "MvtnRejected": "MVTN Rejected",
        "MvtnUpdateAccepted": "MVTN Update Accepted",
        "MvtnUpdateRejected": "MVTN Update Rejected",
        "MonitorPacketReceived": "Monitor Packet Received",
        "GaugeEntersAlarm": "Monitor Alarm",
        "DeviceModeIsPowerSaver": "Device In Power Save Mode",
        "ProactivePathRecalculate": "ProActive Path Recalculated",
        "WanCommunicationError": "WAN Communication Error",
        "PolicySelectionNotAchieved": "No Policy Selected",
        "RabbitMQErrorOccured": "RabbitMQ Error",
        "RadiusServerErrorOccured": "Radius Server Error",
        "LdapClientErrorOccured": "LDAP Client Error",
        "BgpSpeakerConfigurationError": "BGP Speaker Config Error",
        "BgpSpeakerUnconfigurationError": "BGP Speaker Unconfig Error",
        "BgpPeerConfigurationError": "BGP Peer Config Error",
        "BgpPeerUnconfigurationError": "BGP Peer Unconfig Error",
        "BgpPeerConnectionError": "BGP Peer Connection Error",
        "NeedEmergencyPolicy": "Emergency Policy Can Be Applied.",
        "InvalidCredentials": "Login attempt with invalid credentials"
    }
};
