//Auto-generated file, do not modify, use milat_api project to regenerate and update.
export var alarm_codes = {
    "tr": {
        "ControllerDeactivated": "Kontrolcü Deaktive edildi",
        "DBOperationFailed": "Veritabanı İşlemi Başarısız",
        "DeviceIsNotAvailable": "Cihazın Bağlantısı Koptu",
        "LinkDown": "Bağlantı Koptu",
        "MvtnDeviceFailed": "Sanal Ağ Cihazı Başarısız",
        "MvtnLinkFailed": "Sanal Ağ Bağlantısı Koptu",
        "MvtnLinkRebuilt": "Sanal Ağ Bağlantısı Tekrar Oluşturuldu",
        "SelfLoopDetection": "Döngü Keşfedildi",
        "ForwardingLoopDetection": "İletim Döngüsü Keşfedildi",
        "TsdbProviderNotAvailable": "ZSVT Hizmeti Yok",
        "OpenFlowMessageError": "Hatalı OpenFlow Mesajı",
        "DOSAttackDetected": "DOS Saldırısı Tespit Edildi",
        "NorthboundDDosAttack": "Kuzey arayüzünde Servis Engelleme Saldırısı tespit edildi.",
        "EastWestboundDDosAttack": "Doğu/Batı arayüzünde Servis Engelleme Saldırısı tespit edildi.",
        "SouthboundDDosAttack": "Güney arayüzünde Servis Engelleme Saldırısı tespit edildi.",
        "MallwareDetected": "Kötücül yazılım tespit edildi.",
        "SnmpTrapReceived": "SNMP Trap Alındı",
        "ProactivePathFailed": "Önetkin Patika Koptu",
        "MvtnCreated": "Sanal Ağ Oluşturuldu",
        "UnreachableDatabase": "Veritabanına Ulaşılamıyor",
        "EventNotSupportedByCurrentState": "Olay desteklenmiyor",
        "HbaseConnectionError": "HBASE'e bağlanılamıyor",
        "MvtnRejected": "Sanal Ağ Red Edildi",
        "MvtnUpdateAccepted": "Sanal Ağ Güncelleme Kabul Edildi",
        "MvtnUpdateRejected": "Sanal Ağ Güncelleme Red Edildi",
        "MonitorPacketReceived": "Gözcü Paketi Alındı",
        "GaugeEntersAlarm": "Gözcü Alarmı",
        "DeviceModeIsPowerSaver": "Cihaz Enerji Tasarrufu Modunda",
        "ProactivePathRecalculated": "Önetkin Patika Yeniden Hesaplandı",
        "WanCommunicationError": "WAN İletişim Hatası",
        "PolicySelectionNotAchieved": "Politika Seçilemedi",
        "RabbitMQErrorOccured": "RabbitMQ Hatası",
        "RadiusServerErrorOccured": "Radius Sunucu Hatası",
        "LdapClientErrorOccured": "LDAP İstemci Hatası",
        "BgpSpeakerConfigurationError": "BGP Sözcü Konfigürasyon Hatası",
        "BgpSpeakerUnconfigurationError": "BGP Sözcü Nakonfigürasyon Hatası",
        "BgpPeerConfigurationError": "BGP Eş Konfigürasyon Hatası",
        "BgpPeerUnconfigurationError": "BGP Eş Nakonfigürasyon Hatası",
        "BgpPeerConnectionError": "BGP Eş Bağlantı Hatası",
        "NeedEmergencyPolicy": "Acil Durum Politikası Uygulanabilir.",
        "InvalidCredentials": "Geçersiz kullanıcı/şifre ile giriş isteği yapıldı.",
        "NotAllowedDeviceConnection": "İzin Verilmeyen Cihaz Bağlantısı",
        "UnauthorizedSslCertificate": "Yetkisi olmayan SSL Sertifikası",
        "ProactivePathWithdrawn": "Önetkin Patika Düştü",
        "RabbitMQErrorOccurred": "RabbitMQ Hatası",
        "RadiusServerErrorOccurred": "Radius Sunucu Hatası",
        "DrillPacketSentError": "Matkap Paket Hatası",
        "LdapClientErrorOccurred": "LDAP İstemci Hatası",
        "PathNotFound": "Patika Bulunamadı",
        "WanDomainPropertyIsNotValid": "Geniş Ağ Ayarları Geçerli Değil",
        "BgpRouteReflectionWanConfigurationError": "Geniş Ağ'da BGP Route Ayarlama Hatası",
        "BgpRouteReflectionWanUnconfigurationError": "Geniş Ağ'da BGP Route Ayarı Geri Alma Hatası",
        "BgpRouteReflectionConfigurationError": "BGP Route Ayarlama Hatası",
        "BgpRouteReflectionUnconfigurationError": "BGP Route Ayarı Geri Alma Hatası",
        "BgpSpeakerWanConfigurationError": "Geniş Ağ'da BGP Speaker Ayarlama Hatası",
        "BgpSpeakerWanUnconfigurationError": "Geniş Ağ'da BGP Speaker Ayarı Geri Alma Hatası",
        "NotAllowedControllerConnection": "İzin verilmeyen Kontrolcü Bağlantısı",
        "DenialOfServiceAttack": "Service Engelleme Saldırısı tespit edildi.",
        "IntegrityError": "Bütünlük kontrolü hatası",
        "PortDown": "Anahtarlayıcı bağlantı noktası kapatıldı",
        "ControllerModeIsGreen": "Kontrolcü istenirse kapatılabilir durumdadır.",
        "Syslog": "Anahtarlayıcıya dışarıdan bağlantı isteği reddedildi.",
        "DeviceQuarantined": "Uç birim karantinaya aldı."
    },
    "en": {
        "ControllerDeactivated": "Controller Deactivated",
        "DBOperationFailed": "Database Operation Failed",
        "DeviceIsNotAvailable": "Device disconnected",
        "LinkDown": "Link Down",
        "MvtnDeviceFailed": "Mvtn Device Failed",
        "MvtnLinkFailed": "Mvtn Link Failed",
        "MvtnLinkRebuilt": "Mvtn Link Rebuilt",
        "SelfLoopDetection": "Self Loop Detected",
        "ForwardingLoopDetection": "Forwarding Loop Detected",
        "TsdbProviderNotAvailable": "TSDB Provider is N/A",
        "OpenFlowMessageError": "OpenFlow Message Error",
        "DOSAttackDetected": "DOS Attack Detected",
        "NorthboundDDosAttack": "Denial Of Service Attack on Northbound interface is detected.",
        "EastWestboundDDosAttack": "Denial Of Service Attack on East/West interface is detected.",
        "SouthboundDDosAttack": "Denial Of Service Attack on Southbound interface is detected.",
        "MallwareDetected": "Mallware detected.",
        "SnmpTrapReceived": "SNMP Trap Received",
        "ProactivePathFailed": "Proactive Path Failed",
        "MvtnCreated": "MVTN Created",
        "UnreachableDatabase": "Database Unreachable",
        "EventNotSupportedByCurrentState": "Event Not Supported",
        "HbaseConnectionError": "Cannot connect to HBASE",
        "MvtnRejected": "MVTN Rejected",
        "MvtnUpdateAccepted": "MVTN Update Accepted",
        "MvtnUpdateRejected": "MVTN Update Rejected",
        "MonitorPacketReceived": "Monitor Packet Received",
        "GaugeEntersAlarm": "Monitor Alarm",
        "DeviceModeIsPowerSaver": "Device In Power Save Mode",
        "ProactivePathRecalculated": "Proactive Path Recalculated",
        "WanCommunicationError": "WAN Communication Error",
        "PolicySelectionNotAchieved": "No Policy Selected",
        "RabbitMQErrorOccured": "RabbitMQ Error",
        "RadiusServerErrorOccured": "Radius Server Error",
        "LdapClientErrorOccured": "LDAP Client Error",
        "BgpSpeakerConfigurationError": "BGP Speaker Config Error",
        "BgpSpeakerUnconfigurationError": "BGP Speaker Unconfig Error",
        "BgpPeerConfigurationError": "BGP Peer Config Error",
        "BgpPeerUnconfigurationError": "BGP Peer Unconfig Error",
        "BgpPeerConnectionError": "BGP Peer Connection Error",
        "NeedEmergencyPolicy": "Emergency Policy Can Be Applied.",
        "InvalidCredentials": "Login attempt with invalid credentials",
        "NotAllowedDeviceConnection": "Not Allowed Device Connection",
        "UnauthorizedSslCertificate": "Unauthorized SSL Certificate",
        "ProactivePathWithdrawn": "Proactive Path Withdrawn",
        "RabbitMQErrorOccurred": "RabbitMQ Error",
        "RadiusServerErrorOccurred": "Radius Server Error",
        "DrillPacketSentError": "Drill Packer Error",
        "LdapClientErrorOccurred": "LDAP Client Error",
        "PathNotFound": "Path Not Found",
        "WanDomainPropertyIsNotValid": "WAN Domain Configuration Not Valid",
        "BgpRouteReflectionWanConfigurationError": "BGP Route Reflection WAN Configuration Error",
        "BgpRouteReflectionWanUnconfigurationError": "BGP Route Reflection WAN Unconfiguration Error",
        "BgpRouteReflectionConfigurationError": "BGP Route Reflection Configuration Error",
        "BgpRouteReflectionUnconfigurationError": "BGP Route Reflection Unconfiguration Error",
        "BgpSpeakerWanConfigurationError": "BGP Speaker WAN Configuration Error",
        "BgpSpeakerWanUnconfigurationError": "BGP Speaker WAN Unconfiguration Error",
        "NotAllowedControllerConnection": "Not Allowed Controller Connection",
        "DenialOfServiceAttack": "Denial Of Service Attack detected.",
        "IntegrityError": "Integrity Check Error",
        "PortDown": "Port Down",
        "ControllerModeIsGreen": "Controller is in green mod now.",
        "Syslog": "Unauthorized controller connection to switch.",
        "DeviceQuarantined": "Device is quarantined."
    }
};
