//Auto-generated file, do not modify, use milat_api project to regenerate and update.
export var error_codes = {
    "tr": {
        "ERR-1": "Bilinmeyen hata",
        "ERR0": "İşlem Başarılı",
        "ERR1": "Uyarı",
        "ERR2": "Hatalı Parametre",
        "ERR3": "Hatalı Http Uygulama Başlık Parametresi",
        "ERR4": "Hatalı Http Kullanıcı Başlık Parametresi",
        "ERR5": "Http mesajı yazma sırasında hata oluştu",
        "ERR6": "Bulunamadı",
        "ERR7": "Hatalı konfigürasyon.",
        "ERR8": "Doğrulama hatası.",
        "ERR9": "Uzak cevap hatalı",
        "ERR10": "Erişim Engellendi",
        "ERR11": "Erişim Kısıtlandı",
        "ERR12": "Kullanılmıyor",
        "ERR13": "Uygulanmadı",
        "ERR14": "Değişiklik yok",
        "ERR15": "Erişim Engellendi. Sebebi, kullanıcı durumu aktif değil",
        "ERR16": "Erişim Engellendi. Sebebi, kullanıcı parametreleri yanlış",
        "ERR20": "Sayfalama Hatası",
        "ERR21": "Bu uygulamanın maksimum kullanıcı limitine ulaşıldı.",
        "ERR22": "Kulanıcı bulunamadı.",
        "ERR53": "Veritabanı hatası",
        "ERR54": "Dao oluşturma hatası.",
        "ERR55": "Geçersiz dao",
        "ERR56": "Veritabanı çalışmıyor veya veritabanına ulaşılamıyor.",
        "ERR57": "Kademeli silme hatası.",
        "ERR101": "Kullanıcı oturum bilgisi bulunamadı",
        "ERR102": "Kullanıcı oturumunun kimlik doğrulaması yapılamadı",
        "ERR103": "HttpRequest asenkron işlemleri desteklemiyor",
        "ERR104": "Geçersiz kimlik bilgileri",
        "ERR105": "Yetkilendirme başlığı geçersiz",
        "ERR106": "Kullanıcının oturum süresi dolmuş",
        "ERR107": "Kullanıcı oturumu bilinmiyor",
        "ERR108": "Belirtilen rol bir kullanıcı tarafından kullanılmaktadır.",
        "ERR109": "Basic auth sırasında hata oluşru.",
        "ERR110": "Bilinmeyen kullanıcı",
        "ERR111": "Kitlenmiş kullanıcı",
        "ERR112": "Geçersiz eski şifre",
        "ERR113": "Geçersiz yeni şifre",
        "ERR114": "Geçersiz kullanıcı adı",
        "ERR115": "Eski şifre uyuşmuyor",
        "ERR116": "Kullanıcı parametreleri eksiktir.",
        "ERR117": "Parametre eşsiz olmalıdır.",
        "ERR118": "Opsiyonlar girilmelidir",
        "ERR119": "Parametre eşsiz olmalıdır",
        "ERR121": "Kullanıcı Ldap sunucusunda bulunamadı.",
        "ERR150": "Json üretme hatası",
        "ERR151": "Json işleme hatası",
        "ERR200": "Referans geçersiz",
        "ERR201": "Bu servise erişim yetkiniz bulunmamaktadır.",
        "ERR300": "URL geçersiz",
        "ERR301": "Servis veritabanında bulunamadı",
        "ERR302": "Servis sürümü veritabanında bulunamadı",
        "ERR303": "İsteği işlemek için kullanılabilir bir uygulama bulunamadı",
        "ERR304": "İsteği işleyecek REST arayüzü bulunamadı",
        "ERR305": "İstek iletilirken hata oluştu.",
        "ERR400": "POST isteğinin içeriği boş olamaz.",
        "ERR401": "Http talebi önceden tanımlanmış zaman aşımı değerini ulaşmıştır",
        "ERR500": "İç Sunucu Hatası",
        "ERR502": "Veritabanı işlemi başarısız oldu",
        "ERR550": "RabbitMQ sunucusu kapalı veya erişilemiyor",
        "ERR551": "RabbitMQ işlemi tamamlanmadı",
        "ERR552": "Modül özellikler dosyası bulunamadı",
        "ERR523": "Geçersiz REST isteği parametresi",
        "ERR524": "Sonuç kodu ayrıştıma işlemi başarısız oldu",
        "ERR525": "Port listesi boş",
        "ERR526": "VRR arkasında bağlı cihazlar var.",
        "ERR600": "OF limit görüntüleyicisi sadece lider kontrolcü tarafından başlatılıp&#x2F;durdurulabilir.",
        "ERR601": "Verilen OF limitleyicisi görüntülenemiyor.",
        "ERR700": "Akış kuralı oluşturulamadı. Yetersiz bant genişliği!",
        "ERR701": "Akış kuralı oluşturulamadı. Güvenlik seviyesi ihlali!",
        "ERR702": "Sanal ağ oluşturulamadı. Sanal anahtarlayıcı, link veya kullanıcılar geçerli değil!",
        "ERR703": "Geçerli olmayan sanal ağ parametresi!",
        "ERR704": "İlgili sanal ağ durumu operasyon için uygun değil!",
        "ERR705": "Zenginleştirilmiş topoloji henüz hazır değil.",
        "ERR706": "Ovsdb operasyon hatası.",
        "ERR707": "Cihaz bulunamadı.",
        "ERR708": "OpenTSDB başlatılırken hata oluştu.",
        "ERR709": "TSDB sağlayıcısı bulunamıyor.",
        "ERR710": "QUARTZ zamanlayıcı hatası.",
        "ERR711": "Mvtn bulunamadı.",
        "ERR712": "Önetkin patika politikası bulunamadı.",
        "ERR713": "Patika zaten kurulmuş durumda.",
        "ERR714": "Sanağ ağ cihazları geçerli değil.",
        "ERR715": "Sanağ ağ linkleri geçerli değil.",
        "ERR716": "Sanal ağ hostları geçerli değil.",
        "ERR717": "Akış kısıtına uygun patika bulunamadı. Kısıtın java sınıfının adına bakınız.",
        "ERR718": "Önetkin patika kurulamadı.",
        "ERR750": "Oturum açma başarısız.",
        "ERR751": "Kullanıcı oturumu bulunamadı.",
        "ERR752": "Kullanıcı kendisine gelen olayı işleyecek durumda değil.",
        "ERR753": "Host bulunamadı.",
        "ERR754": "Oturum kapama başarısız.",
        "ERR755": "Bu cihaz başka bir kullanıcıya atanmış.",
        "ERR756": "Bu cihaz bu kullanıcıya zaten atanmış durumda.",
        "ERR757": "Bu isimle başka bir erişim grubu zaten mevcut.",
        "ERR999": "Ağ bağlantısında bir problem oluştu",
        "ERR1000": "Konfigürasyon işlemlerinde hata oluştu.",
        "ERR10100": "Son kullanıcı hesabı bulunamadı.",
        "ERR10101": "Son kullanıcı oturumunu bulunamadı.",
        "ERR10102": "Sanal ağ patikası yoksayılan anahtarlayıcılar nedeniyle kurulamadı.",
        "ERR10103": "Sanal ağ seçilmiş fiziksel patika ile kurulamadı. Yeni fiziksel patikalar hesaplandı ve en iyisi varsayılan olarak seçildi.",
        "ERR10104": "Alarm bildirim konfigürasyonu verilen id bilgisine göre veritabanında bulunamadı.",
        "ERR10105": "Sanal ağ operatorleri için alarm bildirim konfigürasyonunda en az bir tane sanal ağ seçili olmalıdır.",
        "ERR10106": "Kullanıcının ilişkilendirildiği sanal ağ için maksimum kullanıcı sayısına ulaşıldığından yeni kullanıcı oluşturulamıyor.",
        "ERR10107": "Aynı Vlan Etiketi daha önceden kullanılmış. Lütfen yeni bir Vlan Etiketi giriniz.",
        "ERR20001": "routerAddress konfigürasyonunda sorunlar var.",
        "ERR20002": "domainServerAddress konfigürasyonunda sorunlar var.",
        "ERR20003": "scope mevcut değil.",
        "ERR20004": "Option mevcut değil.",
        "ERR20005": "Başlangıç ip adresi geçersiz.",
        "ERR20006": "Adres havuzu hatalı.",
        "ERR20007": "Adres havuzu mevcut değil.",
        "ERR20008": "Yasaklanmış ip adresleri hatalı.",
        "ERR20009": "Yasaklanmış ip adresleri bulunmuyor.",
        "ERR20010": "Ayrılmış ip adresleri hatalı.",
        "ERR20011": "Ayrılmış ip adresleri bulunmuyor.",
        "ERR20012": "Görev işlenirken yeni istekte bulunulamaz.",
        "ERR20013": "Enerji tasarrufu modunda olan cihaz mevcut.",
        "ERR20014": "Geçerli olmayan DhcpOption değeri.",
        "ERR21000": "NTOP tipinde network elemanı bulunamadı.",
        "ERR21001": "NTOP elemanı politka tarafından kullanımda.",
        "ERR7001": "Mevcut NSD hala çalışmakta",
        "ERR7000": "Guncellemeye izin verilmiyor",
        "ERR7002": "NSD&#39;ye bağlı olan VNFD başka NSD tarafından kullanılıyor",
        "ERR7003": "Belirtilen VNFD birden çok NSD tarafından kullanılıyor",
        "ERR7004": "Güş tasarrufu modundan dolayı akış kurulamadı.",
        "ERR7005": "Link için verilen gecikme değerinden dolayı akış kurulamadı.",
        "ERR7006": "Link için verilen tip değerinden dolayı akış kurulamadı.",
        "ERR7007": "Link için verilen jitter değerinden dolayı akış kurulamadı.",
        "ERR120": "Aynı lokasyon birden fazla network device tarafından kullanılmamalıdır.",
        "ERR800": "Sdnip yönlendiriciye ulaşılamıyor.",
        "ERR801": "Sdnip yönlendirici hatası.",
        "ERR802": "Sdnip yönlendirici hatası.",
        "ERR803": "Sdnip yönlendiricinin BGP sözcü veya komşu olarak bağlantısı var.",
        "ERR804": "Sdnip yönlendiricinin hatası.",
        "ERR805": "Geniş ağ kontrolcüsü aktif değil.",
        "ERR806": "Lokal WAN bilgileri, merkezi kontrolcüden gelen bilgilerle uyumlu değil",
        "ERR807": "Merkezi kontrolcü henüz aktif ve lokale bağlı değil.",
        "ERR900": "Vnfr bilgisi bulunamadı.",
        "ERR901": "Vnfr&#39;ın bağlı olduğu ağ anahtarlayıcısı, openstack üzerinde çalışıyor.",
        "ERR902": "İlgili Vnfr zaten mevcut.",
        "ERR903": "İlgili Vnfr Sfc tarafından kullanılmaktadır.",
        "ERR904": "Seçilen Vnfr sanal tiptedir.",
        "ERR905": "Seçilen Vnfr aktif değil.",
        "ERR906": "Sfc Vnfr listesi null veya eksik.",
        "ERR907": "Seçilen SFC bulunamadı.",
        "ERR10000": "Ağ cihazının MAC veya VLAN_ID değeri tekil değildir.",
        "ERR10001": "Kontrolcü network device id olarak eklenememektedir.",
        "ERR30000": "Liderlik eventi işlenemedi.",
        "ERR30001": "Ağ geçidi eventi işlenemedi.",
        "ERR30002": "Geleneksel anahtarlayıcı eventi işlenemedi.",
        "ERR30003": "Küme eventi işlenemedi.",
        "ERR30004": "Link eventi işlenemedi.",
        "ERR30005": "Uç birim eventi işlenemedi.",
        "ERR30006": "Cihaz eventi işlenemedi.",
        "ERR30007": "Ip phone eventi işlenemedi.",
        "ERR7017": "OpenStack&#39;ten yetki alınamadı",
        "ERR7008": "OpenBaton&#39;dan yetki alınamadı",
        "ERR7009": "Orkestrasyon&#39;da gecersiz yetkilendirme"
    },
    "en": {
        "ERR-1": "Unknown",
        "ERR0": "Success",
        "ERR1": "Warning",
        "ERR2": "Invalid Parameter",
        "ERR3": "Invalid Http Application Header Parameter",
        "ERR4": "Invalid Http User Header Parameter",
        "ERR5": "Error during writing to http body",
        "ERR6": "Not found",
        "ERR7": "Configuration not valid.",
        "ERR8": "Validation failed.",
        "ERR9": "Remote Response is Invalid",
        "ERR10": "Access Denied",
        "ERR11": "Access Limited",
        "ERR12": "Deprecated",
        "ERR13": "Not Implemented",
        "ERR14": "Not Modified",
        "ERR15": "Access Denied because of inactive user state",
        "ERR16": "Access Denied incorrect credentials",
        "ERR20": "Paging Error",
        "ERR21": "Reached to this application&#39;s maximum user limit.",
        "ERR22": "User not found.",
        "ERR53": "DB Operation Error",
        "ERR54": "Dao creation error.",
        "ERR55": "Invalid dao",
        "ERR56": "Database is down or unreachable.",
        "ERR57": "Cascade delete error.",
        "ERR101": "User session or basic authentication info is not found",
        "ERR102": "User session is not authenticated",
        "ERR103": "HttpRequest does not support asynchronous operations",
        "ERR104": "Invalid credientials",
        "ERR105": "Authorization header is invalid",
        "ERR106": "User Session is expired",
        "ERR107": "User Session is unknown",
        "ERR108": "Selected role is currently being used by a user",
        "ERR109": "Exception occurred during basic authentication&#x2F;authorisation",
        "ERR110": "Unknown account",
        "ERR111": "Locked account",
        "ERR112": "Invalid old password",
        "ERR113": "Invalid new password",
        "ERR114": "Invalid username",
        "ERR115": "Incorrect old password",
        "ERR116": "Null user parameters",
        "ERR117": "Non unique parameter",
        "ERR118": "Options is null",
        "ERR119": "Parameter should be unique",
        "ERR121": "User not found in Ldap server.",
        "ERR150": "Json Serialization Error",
        "ERR151": "Json Deserialization Error",
        "ERR200": "Reference is",
        "ERR201": "You don&#39;t have permission to access this service.",
        "ERR300": "URL is invalid",
        "ERR301": "Service is not found in DB",
        "ERR302": "Service version is not found on DB",
        "ERR303": "Could not found an available instance to handle the request",
        "ERR304": "Available instance did not set restUrl in xx-orchestration.properties file",
        "ERR305": "Exception occurred during request forwarding.",
        "ERR400": "Http POST request body can not be empty",
        "ERR401": "Http Request has reached its predefined timeout value",
        "ERR500": "Internal Server Error",
        "ERR502": "DB operation failed",
        "ERR550": "RabbitMq Server is unreachable or down",
        "ERR551": "RabbitMq Process did not complete",
        "ERR552": "Module Property File doesn&#39;t Exist",
        "ERR523": "Invalid Rest Call Parameter",
        "ERR524": "Result Code Parsing is Failed",
        "ERR525": "Port list is empty",
        "ERR526": "VRR has redundant devices.",
        "ERR600": "OF meter monitoring can only be started&#x2F;stopped by master controller",
        "ERR601": "Given OF meter is not being monitored",
        "ERR700": "Flow rule could not be created. Insufficient bandwith!",
        "ERR701": "Flow rule could not be created. Security level constraint violation!",
        "ERR702": "Mvtn could not be created. Mvtn Devices, Links or Hosts are not valid!",
        "ERR703": "Invalid Mvtn parameter",
        "ERR704": "Cannot perform operation on an mvtn with current state",
        "ERR705": "Enriched topology not available yet",
        "ERR706": "Ovsdb operation error.",
        "ERR707": "Not found device.",
        "ERR708": "OpenTSDB init failed.",
        "ERR709": "TSDB provider is not available.",
        "ERR710": "QUARTZ scheduler error.",
        "ERR711": "Mvtn is not found",
        "ERR712": "Proactive path policy is not found",
        "ERR713": "Path already exists",
        "ERR714": "Mvtn devices are not valid.",
        "ERR715": "Mvtn links are not valid.",
        "ERR716": "Mvtn hosts are not valid.",
        "ERR717": "Path constraint cannot be fulfilled. See name of the constraint java class.",
        "ERR718": "Proactive path could not be created.",
        "ERR750": "Login failed.",
        "ERR751": "User session is not found.",
        "ERR752": "User is not a suitable state to perform incoming event.",
        "ERR753": "Host is not found.",
        "ERR754": "Logout failed.",
        "ERR755": "This device is assigned to another user.",
        "ERR756": "This device is already assigned to this user.",
        "ERR757": "Another NAC group with this name already exists.",
        "ERR999": "Network connection problem occured",
        "ERR1000": "Error occured during config operations.",
        "ERR10100": "End user account not found.",
        "ERR10101": "End user session not found.",
        "ERR10102": "Mvtn path could not be found because of ignored devices.",
        "ERR10103": "Mvtn could not be created with selected physical path. New physical paths are calculated and best solution accepted as default.",
        "ERR10104": "Alarm notification configuration not found in database by given id.",
        "ERR10105": "Alarm notification configuration should be selected with at least one virtual network for virtual operators.",
        "ERR10106": "Number of user for related mvtn has reached the maximum capacity. Therefore new user could not be created with associated mvtn.",
        "ERR10107": "Vlan Tag has created same as before. Please enter new Vlan Tag.",
        "ERR20001": "routerAddress configuration has problems.",
        "ERR20002": "domainServerAddress configuration has problems.",
        "ERR20003": "Scope does not exist.",
        "ERR20004": "Option does not exist.",
        "ERR20005": "Invalid start Ip address.",
        "ERR20006": "Given range has errors.",
        "ERR20007": "Range does not exist.",
        "ERR20008": "Given ip exclusion has errors.",
        "ERR20009": "Ip exclusion does not exist.",
        "ERR20010": "Given ip reservation has errors.",
        "ERR20011": "Ip reservation does not exist.",
        "ERR20012": "Feature is processing now",
        "ERR20013": "Devices are in power saver state",
        "ERR20014": "DhcpOption value is not valid.",
        "ERR21000": "NTOP typed network device not found.",
        "ERR21001": "NTOP device used by policy.",
        "ERR7001": "Specified NSD is still running",
        "ERR7000": "Force update is not allowed",
        "ERR7002": "VNFD element of NSD&#39;s already used by other NSD",
        "ERR7003": "Specified VNFD is bound to NSD",
        "ERR7004": "Flow rule could not be created. Power safe constraint violation!",
        "ERR7005": "Flow rule could not be created. Link delay constraint violation!",
        "ERR7006": "Flow rule could not be created. Link type constraint violation!",
        "ERR7007": "Flow rule could not be created. Link jitter constraint violation!",
        "ERR120": "Same location can not be use more than two network device.",
        "ERR800": "Sdnip router is unreachable or down.",
        "ERR801": "Sdnip Router operation failure.",
        "ERR802": "Sdnip Router operation failure.",
        "ERR803": "Sdnip Router has relation as speaker or peer.",
        "ERR804": "Sdnip module error.",
        "ERR805": "WAN controller is inactive.",
        "ERR806": "Local WAN informations are not consistent with central information",
        "ERR807": "Central controller is not active and is not connected to local yet.",
        "ERR900": "Vnfr not found.",
        "ERR901": "Vnfr host located in openstack node.",
        "ERR902": "Vnfr is allready created.",
        "ERR903": "Vnfr is used by sfc.",
        "ERR904": "Vnfr type is virtual.",
        "ERR905": "Selected Vnfr is not active.",
        "ERR906": "Vnfr list of SFC is null or missing.",
        "ERR907": "SFC not found.",
        "ERR10000": "Network device&#39;s MAC or VLAN_ID is not unique.",
        "ERR10001": "Controller can not add as network device.",
        "ERR30000": "An error occured while processing leadership event.",
        "ERR30001": "An error occured while processing network device event.",
        "ERR30002": "An error occured while processing legacy device event.",
        "ERR30003": "An error occured while processing cluster event.",
        "ERR30004": "An error occured while processing link event.",
        "ERR30005": "An error occured while processing host event.",
        "ERR30006": "An error occured while processing device event.",
        "ERR30007": "An error occured while processing ip phone event.",
        "ERR7017": "OpenStack token couldn&#39;t be retrieved",
        "ERR7008": "OpenBaton token couldn&#39;t be retireved",
        "ERR7009": "Invalid token retrieve of NFVO"
    }
};
