'use strict';

//Model Definition File for ALARM_RESOURCE.js

'use strict';
/**
* Alarmın sebep tipi
*/
exports.ALARM_RESOURCE = {
    type:'enum',
    name:'ALARM_RESOURCE',
    values: ['DEVICE', 'CONTROLLER', 'CONTROLLER_MODE', 'MVTN_LINK', 'LINK', 'MVTN_DEVICE', 'DB', 'NAS_MANAGER', 'TSDB_PROVIDER', 'HBASE', 'MONITOR', 'PATHVLIDATION', 'NONE', 'POLICY_MANAGER', 'PPP_MANAGER', 'SNMP_TRAP', 'PACKET_PROCESSOR', 'RABBIT_MQ', 'RADIUS_SERVER', 'LDAP_CLIENT', 'SSL_AUTH', 'UNALLOWED_DEVICE', 'LOCAL_CONTROLLER', 'CENTRAL_CONTROLLER', 'DRILL', 'SDNIP', 'INTEGRITY', 'EMERGENCY_POLICY', 'INTRUSION_DETECTION_SYSTEM', 'PORT', 'SYSLOG']
}

